# Site settings
author: Aziz Nasirov
title: Programming & Project Journey
header-img: img/home-bg.png
email: nasirovaziz@yahoo.com
copyright_name: Aziz Nasirov
description: > # this means to ignore newlines until "baseurl:"
  learning szn
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  btkelements

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
